submit tags as options for the front matter
azu/jekyll-meta-from-markdown pull request #1
Opened 2017-01-09 02:57 UTC by morriswchris

Added the ability to provide an array of tags for the given file to be added as front matter. Useful for when reading in file names or directory structures a file is apart of.

Sample:

```javascript
jekyllMatter(input, {
  author: "azu",
  date: new Date("2014-09-08T21:38"),
  tags: ["sample", "test"]
})
```

outputs:

```md
---
layout: post
title: "title"
author: azu
date: 2014-09-08T21:38:00.000Z
tags:
  - sample
  - test
---
```

2017-01-09 03:36 UTC, azu requested changes
Thanks for pull request.

I'll merge this after following is fixed.

2017-01-09 03:36 UTC, azu commented on lib/jekyll-meta-from-markdown.js
> +    if (options.tags && options.tags instanceof Array) {
Please use `Array.isArray(options.tags)` insteadof `options.tags instanceof Array`.

2017-01-09 23:24 UTC, morriswchris commented
No problem. Something  found useful.

2017-01-10 00:05 UTC, azu approved these changes

2017-01-10 00:05 UTC, merged

2017-01-10 00:07 UTC, azu commented
Thanks. Merge it adn release https://github.com/azu/jekyll-meta-from-markdown/releases/tag/1.1.0